import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import Sidebar from '../components/Sidebar';
import ProgressRing from '../components/ProgressRing';
import LoadingSpinner from '../components/LoadingSpinner';
import { api } from '../services/api';
import { Cpu, CheckCircle2, AlertTriangle, ArrowRight, ShieldCheck, Sparkles } from 'lucide-react';

export default function Diagnosis({ showToast }) {
  const { id } = useParams();
  const [diagnosis, setDiagnosis] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDiagnosis();
  }, [id]);

  const loadDiagnosis = async () => {
    setLoading(true);
    try {
      const data = await api.runDiagnosis(id);
      setDiagnosis(data);
    } catch (err) {
      showToast('Failed to run AI diagnosis', 'error');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex min-h-[calc(100vh-65px)]">
        <Sidebar deviceId={id} />
        <main className="flex-1 flex items-center justify-center">
          <LoadingSpinner label="Object & Condition Agents evaluating device integrity..." />
        </main>
      </div>
    );
  }

  if (!diagnosis) return null;

  return (
    <div className="flex min-h-[calc(100vh-65px)]">
      <Sidebar deviceId={id} />

      <main className="flex-1 p-4 md:p-8 max-w-6xl mx-auto space-y-8 overflow-y-auto">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-emerald-400 text-xs font-mono mb-1">
              <Cpu className="w-4 h-4" />
              <span>AI DIAGNOSIS ENGINE REPORT</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-slate-100 tracking-tight">
              Hardware Integrity & Circular Valuation
            </h1>
            <p className="text-xs md:text-sm text-slate-400 mt-1">
              Diagnosis results generated by Object Identification Agent and Condition Assessment Agent.
            </p>
          </div>

          <Link
            to={`/agents/${id}`}
            className="bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold px-4 py-2.5 rounded-xl text-xs flex items-center gap-2 transition-colors self-start md:self-auto"
          >
            <Sparkles className="w-4 h-4 text-emerald-400" />
            <span>Inspect Agent Logs</span>
          </Link>
        </div>

        {/* Circular Progress Rings Card */}
        <div className="glass-card p-6 md:p-8 rounded-3xl border border-slate-800 bg-slate-900/80">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-center text-center">
            <ProgressRing score={diagnosis.usabilityScore} size={140} label="Usability Score" />
            <ProgressRing score={diagnosis.repairabilityScore} size={140} label="Repairability Index" />
            <ProgressRing score={diagnosis.circularScore} size={140} label="Circular Economy Score" />
          </div>
        </div>

        {/* Diagnosis Summary & Component Health */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Summary Box */}
          <div className="md:col-span-2 glass-card p-6 rounded-3xl border border-slate-800 bg-slate-900/60 space-y-4">
            <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-emerald-400" />
              Agent Diagnosis Summary
            </h3>

            <p className="text-sm text-slate-300 bg-slate-950 p-4 rounded-2xl border border-slate-800/80 leading-relaxed">
              {diagnosis.diagnosisSummary}
            </p>

            {/* Component Health Breakdown */}
            <div className="space-y-2">
              <h4 className="text-xs font-mono text-slate-400 uppercase font-semibold">Subsystem Integrity Breakdown</h4>
              {[
                { comp: 'Display & Touch Glass', health: 96, status: 'Optimal' },
                { comp: 'Battery & Power Subsystem', health: 78, status: 'Service Recommended' },
                { comp: 'Logic Board & Processor', health: 98, status: 'Optimal' },
                { comp: 'Chassis & Enclosure', health: 88, status: 'Good' },
                { comp: 'Ports & Wireless Antennas', health: 94, status: 'Optimal' },
              ].map((item, idx) => (
                <div key={idx} className="flex items-center justify-between p-3 rounded-xl bg-slate-950/60 border border-slate-800/60 text-xs">
                  <span className="font-medium text-slate-200">{item.comp}</span>
                  <div className="flex items-center gap-3">
                    <div className="w-24 bg-slate-800 h-2 rounded-full overflow-hidden">
                      <div 
                        className={`h-full ${item.health > 85 ? 'bg-emerald-500' : 'bg-amber-500'}`} 
                        style={{ width: `${item.health}%` }}
                      />
                    </div>
                    <span className="font-mono text-emerald-400 font-bold w-8">{item.health}%</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Pathway Side Card */}
          <div className="glass-card p-6 rounded-3xl border border-slate-800 bg-gradient-to-b from-slate-900 to-slate-950 flex flex-col justify-between">
            <div>
              <span className="text-xs font-mono uppercase text-emerald-400 font-semibold tracking-wider">
                Optimal Decision Path
              </span>
              <h4 className="text-lg font-bold text-slate-100 mt-1">Recommended Pathway</h4>
              
              <div className="mt-4 p-4 rounded-2xl bg-slate-950 border border-slate-800 text-xs font-medium text-slate-200">
                {diagnosis.recommendedPath}
              </div>

              <div className="mt-4 bg-slate-950 p-3 rounded-xl border border-slate-800 text-xs">
                <span className="text-slate-400 block">Estimated Residual Value:</span>
                <span className="text-xl font-extrabold text-emerald-400 font-mono mt-1 block">
                  ${diagnosis.estimatedValuationUsd} USD
                </span>
              </div>
            </div>

            <Link
              to={`/matches/${id}`}
              className="mt-6 w-full py-3 bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold rounded-xl text-xs flex items-center justify-center gap-2 transition-all shadow-md shadow-emerald-500/20"
            >
              <span>View Recipient Matches</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

        </div>

      </main>
    </div>
  );
}
