from pydantic import BaseModel, Field
from typing import List, Optional

class ImageAnalysisResult(BaseModel):
    """
    Schema representing the outputs generated by a Computer Vision model or AI vision agent.
    """
    detected_category: str = Field(..., description="Detected device category (e.g., Laptop, Monitor)")
    detected_subcategory: Optional[str] = Field(None, description="Granular classification")
    predicted_brand: Optional[str] = Field(None, description="Identified brand")
    predicted_model: Optional[str] = Field(None, description="Identified model")
    visible_damage: List[str] = Field(default_factory=list, description="Damages identified visually")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Overall model inference confidence")

class ImageAnalyzer:
    """
    Abstraction layer for image-based device analysis.
    This class acts as an interface for future computer-vision pipeline integration.
    """
    def __init__(self, service_url: Optional[str] = None):
        self.service_url = service_url

    def analyze_image(self, image_url: str) -> ImageAnalysisResult:
        """
        Sends the image to the vision processing endpoint or runs local inference.
        Returns a structured ImageAnalysisResult.
        
        Currently returns mock detections based on URLs for demonstration/testing.
        """
        # Mock logic based on keywords in URL/filename
        image_lower = image_url.lower()
        
        if "laptop" in image_lower:
            return ImageAnalysisResult(
                detected_category="Laptop",
                detected_subcategory="Notebook",
                predicted_brand="Dell",
                predicted_model="Latitude 5420",
                visible_damage=["scratched_casing"],
                confidence_score=0.92
            )
        elif "monitor" in image_lower:
            return ImageAnalysisResult(
                detected_category="Monitor",
                detected_subcategory="LED Monitor",
                predicted_brand="HP",
                predicted_model="E243",
                visible_damage=[],
                confidence_score=0.95
            )
        elif "phone" in image_lower or "mobile" in image_lower:
            return ImageAnalysisResult(
                detected_category="Smartphone",
                detected_subcategory="Mobile Phone",
                predicted_brand="Apple",
                predicted_model="iPhone 11",
                visible_damage=["cracked_screen"],
                confidence_score=0.88
            )
        else:
            return ImageAnalysisResult(
                detected_category="Unknown",
                detected_subcategory=None,
                predicted_brand=None,
                predicted_model=None,
                visible_damage=[],
                confidence_score=0.50
            )
